[
  {
    Yes: 5,
    No: 1,
    ja: 5,
    nee: 1,
    "Strongly Disagree": 1,
    Disagree: 2,
    Neutral: 3,
    Agree: 4,
    "Strongly Agree": 5,
    "Helemaal oneens": 1,
    Oneens: 2,
    Neutraal: 3,
    Eens: 4,
    "Helemaal eens": 5,
    Never: 1,
    Rarely: 2,
    Sometimes: 3,
    Often: 4,
    Always: 5,
    Nooit: 1,
    Zelden: 2,
    Soms: 3,
    Vaak: 4,
    Altijd: 5,
    "Not at all Important": 1,
    "Slightly Important": 2,
    "Moderately Important": 3,
    "Very Important": 4,
    "Extremely Important": 5,
    "Helemaal niet belangrijk": 1,
    "Een beetje belangrijk": 2,
    "Matig belangrijk": 3,
    "Erg belangrijk": 4,
    "Extreem belangrijk": 5,
    "Very Unlikely": 1,
    Unlikely: 2,
    Neutral: 3,
    Likely: 4,
    "Very Likely": 5,
    "Zeer Onwaarschijnlijk": 1,
    Onwaarschijnlijk: 2,
    Neutraal: 3,
    Waarschijnlijk: 4,
    "Zeer Waarschijnlijk": 5,
    "Very Dissatisfied": 1,
    Dissatisfied: 2,
    Neutral: 3,
    Satisfied: 4,
    "Very Satisfied": 5,
    "Zeer ontevreden": 1,
    Ontevreden: 2,
    Neutraal: 3,
    Tevreden: 4,
    "Zeer tevreden": 5,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
  },
];
